### ISSUE TITLE
XSite Port 7900 Not Exposed

### ISSUE THREAD

**Issue by timothymathison** [infinispan/infinispan-images#101]
When trying to configure infinispan for cross-site replication, communication fails because the port (`7900`) commonly used for the jgroups relay used for establishing the cross-site view [is not exposed](https://github.com/infinispan/infinispan-images/blob/d4b73edf43b40ad06b490e21ab9c21076483121b/server-dev-jdk.yaml#L13).

Is this by design, or is there something I'm missing with this? I believe this is the issue because building my own images which exposes `7900` resolves the communication issues I was encountering.

**Comment by dmvolod** [comment]
@timothymathison you are welcome to create PR
@ryanemerson are you agree?

**Comment by ryanemerson** [comment]
@pruivo Does this make sense? I'm not really familiar with the xsite requirements.

**Comment by pruivo** [comment]
:+1:

**Comment by ryanemerson** [comment]
@timothymathison Fixed in the latest tag `11.0.4.Final-2`
