### ISSUE TITLE
Allow custom server configuration to be provided

### ISSUE THREAD

**Issue by ryanemerson** [infinispan/infinispan-images#12]
It should be possible for users to provide a complete `infinispan.xml` to the server before startup.

**Comment by rigazilla** [comment]
There will still be and additional setup phase on the image side?
It would be interesting to have an Infinispan "naked" image with everything (xml, secrets, maps) mounted from the user or the operator and just a bin/server.sh entry point....
don't know if it's actually possible

**Comment by ryanemerson** [comment]
There will need to be some input to the image as currently the [launch script]( https://github.com/infinispan/infinispan-images/blob/master/modules/runtime/added/bin/launch.sh) generates credentials/xml etc, so there will have to be some mechanism to prevent this when config files are provided by the user.

One very simple option is that we just say that users have to also mount there own `/opt/infinispan/bin/launch.sh`. Something as simple as:

```bash
#!/bin/sh
exec ${ISPN_HOME}/bin/server.sh -c <mounted-config-location>
```

**Comment by gustavonalle** [comment]
The previous image would accept the custom file as an argument:
https://github.com/jboss-dockerfiles/infinispan/tree/9.4.x/server#starting-with-a-custom-configuration

This would avoid the user having to override the full launch script which may contain other logic that affects other startup options of the server

**Comment by gustavonalle** [comment]
For example: one thing I found out is that the config file is manipulated with the config-generator so that it has 
```xml
<inet-address value='172.17.0.2'/>
```

But when using the entrypoint as simply  ```server.sh```,  it will cause the container to be inaccessible since it defaults to 
```xml
<interface name="public">
            <inet-address value="${infinispan.bind.address:127.0.0.1}"/>
</interface>
```

**Comment by ryanemerson** [comment]
Adding summary of zulip conversation for completeness.

The issue with the bind address can be overcome by adding the `-b SITE_LOCAL` to the `server.sh` command.

So it's possible to overwrite the `launch.sh` file with the following:

```bash
#!/bin/sh
exec ${ISPN_HOME}/bin/server.sh -b SITE_LOCAL -c <mounted-config-location>
```

Or directly with a docker command via:

```bash
docker volume create example-vol
cp custom-infinispan.xml custom-jgroups.xml /var/lib/docker/volumes/example-vol/_data
docker run -it -v example-vol:/user-config --entrypoint "/opt/infinispan/bin/server.sh"  infinispan/server:10.0.0.Final-1 -b SITE_LOCAL -c /user-config/custom-infinispan.xml
```
