### ISSUE TITLE
Server inet-address should be 0.0.0.0 by default

### ISSUE THREAD

**Issue by ryanemerson** [infinispan/infinispan-images#122]
Currently we bind the endpoint inet-address to the containers host address, instead this should be bound to `0.0.0.0`

**Comment by ryanemerson** [comment]
Fixed in Infinispan 12.1.3.Final images.

**Comment by ryanemerson** [comment]
Reverting commit in 2.1.7.Final of config-generator as this causes issues with HotRod inside k8s and requires more investigation.

```java
[HotRod-client-async-pool-1-1] WARN  org.infinispan.HOTROD- ISPN004005: Error received from the server: java.lang.IllegalArgumentException: No interface address matching /10.128.3.105
```

**Comment by tristantarrant** [comment]
Since https://issues.redhat.com/browse/ISPN-13331 is in, we can restore this
