### ISSUE TITLE
Config generation step should be optional at startup

### ISSUE THREAD

**Issue by rigazilla** [infinispan/infinispan-images#126]
Adding an envvar to skip config generation step at startup could allow user to provide a full custom configuration for Infinispan if required.
If config generation is disable, all the missing pieces needed by the image to run must be provided by  the user.
config generation should be on by default.

**Comment by ryanemerson** [comment]
Closing as from 13.x the config-generator is only executed if the deprecated env vars `CONFIG_PATH`, `IDENTITIES_PATH` or `ADMIN_IDENTITIES_PATH` are provided.
