### ISSUE TITLE
Config generator should support external configuration use case

### ISSUE THREAD

**Issue by rigazilla** [infinispan/infinispan-images#127]
not a clear requirement atm
Support for this use case should be provided, the user want to:
- generate a configuration externally (use config generator outside the pod)
- apply some custom changes
- run the image on docker or k8s

To allow this the configgenerator should be able to:
- run locally
- generate all the conf files
- generate support for docker and k8s: i.e. the launch command with all the `-v` options or a set of .yaml for k8s

**Comment by ryanemerson** [comment]
What's the use-case for using config-generator outside of the image?

> * run locally
> * generate all the conf files

These are both already possible. The config-generator artifact generates config based upon it's initial args, it doesn't do anything specific to k8s.

Man file:
```
Usage: config-generator [--admin-identities=<adminIdentities>] [-c=<server>]
                        [-i=<identities>] output-dir
      output-dir          The directory where the generated files will be saved
      --admin-identities=<adminIdentities>
                          Yaml file used to initialize admin identities
  -c, --config=<server>   Yaml file used to generate Infinispan configuration
  -i, --identities=<identities>
                          Yaml file used to initialize identities
```

**Comment by ryanemerson** [comment]
Closing as the config-generator has been deprecated from 13.x in favour of users providing the server configuration directly: https://github.com/infinispan/infinispan-images#server-configuration
