### ISSUE TITLE
Allow custom JGroups stacks to be provided by the user

### ISSUE THREAD

**Issue by ryanemerson** [infinispan/infinispan-images#13]
It should be possible for the users to provide custom jgroups stacks via a mounted volume, providing the location of the file via an entry in the config yaml. The generated `infinispan.xml` file should then automatically add said stack file and utilise it for cluster communication.

**Comment by magullo** [comment]
I have slightly modified the template to include a variable multicast address, and changed ConfigGenerator.groovy to default address:

[edit_content.diff.txt](https://github.com/infinispan/infinispan-images/files/3840762/edit_content.diff.txt)

Is this the right way to proceed? We are using this slightly patched version to generate our infinispan docker images.
I thought the config.yml could be:
`jgroups:
  transport: udp
  mcastAddress: "234.6.7.8"
  mcastPort: "45678"
  ...
`

**Comment by ryanemerson** [comment]
@magullo If you're not adverse to configuring Infinispan via xml, it might be easier to provide your own xml for Infinispan and Jgroups. I have just added a section to the README to clarify how this can be achieved: https://github.com/infinispan/infinispan-images/blob/master/README.md#custom-infinispan-xml-configuration.

**Comment by magullo** [comment]
> 
> 
> @magullo If you're not adverse to configuring Infinispan via xml,
Thank you, I will do as you suggest. Still, a couple of yaml lines are much easier to maintain than a full xml.

**Comment by ryanemerson** [comment]
Closing. The config-generator has been deprecated since 13.x. Users should provide their required server configuration directly to the image: https://github.com/infinispan/infinispan-images#server-configuration
