### ISSUE TITLE
Handle the generate-self-signed-certificate-host for connector TLS

### ISSUE THREAD

**Issue by rigazilla** [infinispan/infinispan-images#15]
Policy should be something like: 

if profile is `developer` and no custom certificates nor service cert service are provided then let Infinispan generates self signed certificates for TLS

**Comment by ryanemerson** [comment]
@rigazilla I don't want to tightly couple the image and the operator, so the profile semantics should be in the operator itself. In the image, we could expose the option to generate a self signed certifacte via the yaml.

Maybe:
```yaml
keystore:
   alias: 
   path: /blah 
   password: easdas
   selfSignCert: true
```

With `selfSignCert` being false by default and ignored if `keystore.crtPath` is specified. The operator is then responsible for setting `selfSignCert=true` if required based upon the operator semantics. WDYT?

**Comment by rigazilla** [comment]
@ryanemerson sounds fine, I can work on it
