### ISSUE TITLE
native ARM image

### ISSUE THREAD

**Issue by jeffhubLR** [infinispan/infinispan-images#165]
With the increasing usage of ARM-based systems (minimally: AWS Graviton, Apple M1) it would be greatly beneficial to have an ARM image of infinispan-server.

**Comment by ffraz** [comment]
> With the increasing usage of ARM-based systems (minimally: AWS Graviton, Apple M1) it would be greatly beneficial to have an ARM image of infinispan-server.

try to use "docker pull ffraz/infinispan-server: 13.0.5.Final-1" only for test

**Comment by tristantarrant** [comment]
I have published a new release of the 13.0.5.Final images to quay.io and docker hub with both linux/amd64 and linux/arm64 platforms. 

quay.io/infinispan/server:13.0.5.Final-2
infinispan/server:13.0.5.Final-2

This does not resolve the issue yet: we need to have full build automation in place

**Comment by tristantarrant** [comment]
I believe this can be closed now @ryanemerson
