### ISSUE TITLE
Add support for defining Caches at startup

### ISSUE THREAD

**Issue by mycroft11** [infinispan/infinispan-images#17]
It would be very helpful if we can pass in a list of pre-defined caches so that clients are always guaranteed to have them available? This is particularly useful when deploying to AWS Beanstalk in single container mode.

**Comment by ryanemerson** [comment]
To enable this behaviour, we should make the image process a configured [CLI batch file]() on startup. This provides greater flexibility than simply providing a `cache.xml` file as it will be possible to configure other resources such as counters and users.

**Comment by ryanemerson** [comment]
This will require changes to the Infinispan server which are tracked by [ISPN-12052](https://issues.redhat.com/browse/ISPN-12052)

**Comment by gordillo-ramon** [comment]
Is it possible to define a new CRD in the infinispan operator to define de caches, so it is the operator the one that consolidates that cache list, same as [topic operator for strimzi](https://strimzi.io/docs/operators/master/quickstart.html#key-features-operators_str)?

**Comment by tristantarrant** [comment]
https://github.com/infinispan/infinispan-operator/issues/224

**Comment by rigazilla** [comment]
> Is it possible to define a new CRD in the infinispan operator to define de caches, so it is the operator the one that consolidates that cache list, same as [topic operator for strimzi](https://strimzi.io/docs/operators/master/quickstart.html#key-features-operators_str)?

This features will be available in ver. 2.0.0. 
Good reference is also the PR https://github.com/infinispan/infinispan-operator/pull/360
