### ISSUE TITLE
config-generator binary required to build our own image from infinispan server source

### ISSUE THREAD

**Issue by bikashkumars** [infinispan/infinispan-images#193]
We want to Build Infinispan 11.0.5 container image from source and we don't want to use docker hub image, our application need some extra files during runtime, but i found these 4 files are not part of infinispan source code.

I got to know that, one of the file which we need "config-generator" is not part of source  11.0.x https://infinispan.org/download-archive.
Basically we don't need config-generator during docker build time but we need it during application run time.

How where i can find config-generator ?

While exploring i found mvn package of config-generator at following mvn https://search.maven.org/artifact/org.infinispan.images/config-generator/2.1.0.Dev05/jar

But where i can find binary of config-generator ?

While exploring dockerImage code on github, i found you have committed following
tar --strip-components=1 -xvf /tmp/artifacts/config-generator-src.tar.gz
mvn package -DskipTests=true -Pnative
cp config-generator/target/config-generator-*-runner /opt/config-generator

@ryanemerson

**Comment by ryanemerson** [comment]
> We want to Build Infinispan 11.0.5 container image from source and we don't want to use docker hub image

Can you explain your desired use-case? It might be possible to achieve what you desire without having to create your own image.

> But where i can find binary of config-generator ?

The 11.0.5 container uses config-generator 2.0.3.Final which can be built from the following [tag](https://github.com/infinispan/infinispan-image-artifacts/tree/2.0.3.Final) with `mvn package -DskipTests=true -Pnative`.

You will need GraalVM 20.2.0 and `GRAALVM_HOME` set in order for this to work.

I would strongly recommend upgrading to Infinispan 13.0.10.Final if possible

**Comment by bikashkumars** [comment]
Thanks for your response. Due to Security reason, we build all 3pp images in our pipeline that is the hard requirement.

Also i found, following files as part of docker image present on dockerHub 11.0.x , but from where i can get these files.
- generated-identities.yaml
- java-opts.sh
- jgroups-tcp.xml

@ryanemerson

**Comment by ryanemerson** [comment]
> * generated-identities.yaml

I'm not sure what this file is TBH.

> * java-opts.sh

https://github.com/infinispan/infinispan-images/blob/11.0.x/modules/org/infinispan/distribution/jvm/added/bin/java-opts.sh


> * jgroups-tcp.xml

https://github.com/infinispan/infinispan-image-artifacts/blob/2.0.3.Final/config-generator/src/main/resources/templates/jgroups-tcp.xml

**Comment by bikashkumars** [comment]
Thanks @ryanemerson.
