### ISSUE TITLE
Add support for basic user/pass env variables

### ISSUE THREAD

**Issue by ryanemerson** [infinispan/infinispan-images#2]
In the [old image](https://github.com/jboss-dockerfiles/infinispan/tree/9.4.x/server) it was possible to provide a single user/password combo to the image in order to quickly start the image.  We should provide similar env variables to allow easy development of clients without the need to mount the yaml files required for non-dev environments.

**Comment by gustavonalle** [comment]
As it happened before, it could be nice to generate a random pass if the user did not pass any
