### ISSUE TITLE
Avoid to set bind-address if not defined

### ISSUE THREAD

**Issue by antonionappi88** [infinispan/infinispan-images#202]
Hello,
I'm using Podman to startup an infinispan cluster on multiple machines using Puppet.
I'm having an issue with the way the bind address is configured. I pass to podman a volume with the infinispan.xml configuration file (and the -c option as argument to the entrypoint) but the listen address in the file is ignored because the launch.sh script, if it doesn't find the bind address argument, it sets automatically it to 0.0.0.0. 
Is there a way to change this behaviour without be force to specify the bind address or extending the image ? 

Another option that I was thinking is that I could just overwrite the launch.sh file using a volume... 

Cheers,
Antonio

**Comment by ryanemerson** [comment]
@antonionappi88 The default bind address for a standalone server is `127.0.0.1`, so you can just pass `--bind-addres=127.0.0.1` to replicate this behaviour.

**Comment by antonionappi88** [comment]
Hi @ryanemerson ,
my issue was that i need to dinamically change that that's why I would prefer to not use --bind-address. At the end I solved in puppet defining facts inside the hiera. this can be probably close.

Thanks for your answer anyway!
