### ISSUE TITLE
Update 13.0 image

### ISSUE THREAD

**Issue by evilrussian** [infinispan/infinispan-images#230]
Hi. There is 13.0.22.Final version of infinispan with important issue https://github.com/infinispan/infinispan/pull/12254 fix. Can you build image with new version and publish to infinispan/server docker registry? 
Thanks.

**Comment by ryanemerson** [comment]
Image released to `quay.io/infinispan/server` and `infinispan/server`.

I strongly recommend that you upgrade to Infinispan 15.0.x as 13.0.x no longer receives bug or CVE fixes https://github.com/infinispan/infinispan/blob/main/SECURITY.md
