### ISSUE TITLE
liveness and readyness probes don't parse the correct config if a custom xml file is provided

### ISSUE THREAD

**Issue by jbtrystram** [infinispan/infinispan-images#25]
It looks like the `probe-common.sh` will always parse `${ISPN_HOME}/server/conf/infinispan.xml` even if a custom config is provided with `-c`. 

Anyway, when providing a custom config, the container is never ready in kubernetes, the readyness probe outputs : 
```
curl: (35) error:1408F10B:SSL routines:ssl3_get_record:wrong version number
```

**Comment by ryanemerson** [comment]
> It looks like the `probe-common.sh` will always parse `${ISPN_HOME}/server/conf/infinispan.xml` even if a custom config is provided with `-c`.

If you're providing a custom entry point for the image, it's not really possible for the name of the configuration file to be known by the probes. One solution would be for an environment variable to be utilised by the probes to determine the config name, with this being explicitly set by the custom entry point or at container runtime. However, this isn't a route I want to go down as it is yet another configuration param. I think the easiest solution is to either:

1. Provide your custom config as `infinispan.xml`
2. Write your own probe scripts as required




> Anyway, when providing a custom config, the container is never ready in kubernetes, the readyness probe outputs :
> 
> ```
> curl: (35) error:1408F10B:SSL routines:ssl3_get_record:wrong version number
> ```

Can you provide me with your custom xml, I need to see the endpoint/security configuration to ascertain what could be going wrong.

**Comment by jbtrystram** [comment]
>     1. Provide your custom config as `infinispan.xml`

And i would need to get the config into `/opt/infinispan/server/conf/infinispan.xml` as well, right ?

> Can you provide me with your custom xml, I need to see the endpoint/security configuration to ascertain what could be going wrong.

```
<infinispan
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="urn:infinispan:config:10.0 http://www.infinispan.org/schemas/infinispan-config-10.0.xsd
                                urn:infinispan:server:10.0 http://www.infinispan.org/schemas/infinispan-server-10.0.xsd"
            xmlns="urn:infinispan:config:10.0"
            xmlns:server="urn:infinispan:server:10.0">

       <cache-container name="clustered" statistics="true">
          <transport cluster="${infinispan.cluster.name}" stack="kubernetes"/>
                    
             <replicated-cache name="LuceneIndexesLocking">
                <indexing index="NONE" />
             </replicated-cache>
                    
             <replicated-cache name="LuceneIndexesMetadata">
                <indexing index="NONE" />
             </replicated-cache>
                    
             <distributed-cache name="LuceneIndexesData">
                <indexing index="NONE" />
             </distributed-cache>

             <distributed-cache owners="3" mode="SYNC" remote-timeout="15000" name="devices">
                <locking isolation="READ_COMMITTED"/>
                <indexing index="PRIMARY_OWNER">
                   <property name="default.indexmanager">
                               org.infinispan.query.indexmanager.InfinispanIndexManager
                   </property>
                </indexing>
             </distributed-cache>
             
             <distributed-cache-configuration name="distributed-volatile-cache-template">
             
                <transaction mode="NONE"/>
                <indexing index="NONE"/>
              </distributed-cache-configuration>

             <distributed-cache owners="3" mode="SYNC" remote-timeout="15000" name="adapterCredentials">
                <transaction mode="NONE"/>
                <indexing index="NONE"/>
             </distributed-cache>

             <distributed-cache owners="3" mode="SYNC" remote-timeout="15000" name="deviceStates">
                <transaction mode="NONE"/>
                <indexing index="NONE"/>
             </distributed-cache>
                   
       </cache-container>

       <server xmlns="urn:infinispan:server:10.0">
          <interfaces>
             <interface name="public">
                <inet-address value="${infinispan.bind.address:127.0.0.1}"/>
             </interface>
          </interfaces>

          <socket-bindings default-interface="public" port-offset="${infinispan.socket.binding.port-offset:0}">
             <socket-binding name="default" port="${infinispan.bind.port:11222}"/>
             <socket-binding name="memcached" port="11221"/>
          </socket-bindings>

          <security>
             <security-realms>
                <security-realm name="default">
                   <properties-realm groups-attribute="Roles">
                      <user-properties path="users.properties" relative-to="infinispan.server.config.path"/>
                      <group-properties path="groups.properties" relative-to="infinispan.server.config.path" />
                   </properties-realm>
                </security-realm>
             </security-realms>
          </security>

          <endpoints socket-binding="default" security-realm="default">
             <hotrod-connector name="hotrod"/>
             <rest-connector name="rest"/>
             <!-- Uncomment to enable the memcached connector -->
             <!-- memcached-connector socket-binding="memcached" / -->
          </endpoints>
       </server>
    </infinispan>
```

**Comment by ryanemerson** [comment]
The reason th

> Anyway, when providing a custom config, the container is never ready in kubernetes, the readyness probe outputs :
> 
> ```
> curl: (35) error:1408F10B:SSL routines:ssl3_get_record:wrong version number
> ```

This is because the probe is trying to use `HTTPS`, however ssl is not defined in your configuration. As there are many permutations with custom configuration, I think it's best just to define your own readiness/liveness probes when providing a custom configuration.

**Comment by jbtrystram** [comment]
I am working on defining my own probe, but the `rest/v2/cache-managers/DefaultCacheManager/health/status` return `404 not found`. Is there something specific I need to set in the xml config file to get the endpoint properly enabled ?
