### ISSUE TITLE
Allow JGroups Diagnostics to be configured

### ISSUE THREAD

**Issue by ryanemerson** [infinispan/infinispan-images#26]
The jgroups discovery protocols should have `enable_diagnostics=true` as the default behaviour to provide more debugging options. This should not be a security issue, as it's necessary for the port to be explicitly exposed by the container environment.

**Comment by slaskawi** [comment]
I'm not sure if this is a good idea. This might be considered as a security problem (I may use Probe to mess up your cluster - especially if you're using Load Balancers with public IPs). 

I would prefer to create an env variable (`DEBUG` or something) that would need to be explicitly turned on.

**Comment by ryanemerson** [comment]
Thanks for the speedy feedback :smiley: 

When discussing this last week with Bela the conclusion was that enabling diagnostics is acceptable, because in an environment such as kubernetes, the diagnostics port has to be explicitly exposed in order for it to be accessible externally.

WDYT is this sufficient protection?

**Comment by slaskawi** [comment]
I would still prefer to have a debug option in the image.

The solution you proposed works fine if you handcraft all Kubernetes objects. But there are users using some tooling (`oc expose`, `odo` or probably other tools as well) that might grab all ports from the `EXPOSE` instruction of the image and try to expose it automatically. This way you might be exposing diagnostic port without knowing it.

**Comment by ryanemerson** [comment]
The default diagnostics_port for jgroups is 7500 which we don't expose in the image anyway. So AFAIK the only way to access this port would be by executing code within the container or if a user extended the image in order to explicitly expose the port.

But I will play it safe and associate this behaviour with the existing `DEBUG` env variable and we can re-asses later if this is problematic.

**Comment by ryanemerson** [comment]
In the end I added this to the yaml configuration as:

```yaml
jgroups:
  diagnostics: true | false
```

**Comment by slaskawi** [comment]
Great! Thanks @ryanemerson

**Comment by belaban** [comment]
+1
