### ISSUE TITLE
Store hashed credential identities

### ISSUE THREAD

**Issue by ryanemerson** [infinispan/infinispan-images#6]
Currently we store key/values in plain text as it's necessary for our probe implementations to authenticate with the rest endpoint in order to retrieve health information. Once https://github.com/infinispan/infinispan/pull/7248 has been merged, it will be possible to request this information anonymously, therefore we should no longer store credentials in plain-text.

**Comment by galderz** [comment]
I think this means we can get rid of the operator user we were using for the probes, is that right? /cc @rigazilla

**Comment by rigazilla** [comment]
> I think this means we can get rid of the operator user we were using for the probes, is that right? /cc @rigazilla

@galderz https://github.com/infinispan/infinispan/pull/7248  allows unauth access for health and ready probes, but operator needs to call other API resources: cluster info, graceful shutdown and maybe others... that can't be unauthenticated.

We still need a kind of authenticated way for the operator/infinispan interaction.
