### ISSUE TITLE
Able to customize and set server.interfaces.<interface>.inet-address in infinispan.xml

### ISSUE THREAD

**Issue by dmvolod** [infinispan/infinispan-images#81]
It would be nice to introduce a new option in Config Yaml and set it to the following config section instead of _jgroups.bindAddress_
```
<interfaces>
  <interface name="public">
    <inet-address value="{jgroups.bindAddress}"/>
  </interface>
</interfaces>
```
It restricts to use port forwarding as by default Infinispan server binds to the specific ip address, but oc port-forward awaits to be on loop-back interface or on all interfaces as described in https://github.com/infinispan/infinispan-operator/issues/464.

@ryanemerson is it possible to bind Infinispan on the 0.0.0.0 or customize this option?

**Comment by ryanemerson** [comment]
@dmvolod Thanks for raising this issue. I have created https://github.com/infinispan/infinispan-image-artifacts/pull/21 which makes it so the default bind address is 127.0.0.1, but the IP can be updated via a java property (same as our normal server distribution) like so: `podman run -e JAVA_OPTIONS="-Dinfinispan.bind.address=0.0.0.0" infinispan/server`. This will be available in the 12.x stream.

**Comment by dmvolod** [comment]
Thanks for quick response, @ryanemerson 
Is there any chance to backport this option to the Infinspan 11.x version as this was reported by Data Grid 8.x and based on Infinspan 11.x.

**Comment by ryanemerson** [comment]
I've created https://github.com/infinispan/infinispan-image-artifacts/pull/22, however this won't make it until 11.0.2

**Comment by dmvolod** [comment]
Thanks a lot, @ryanemerson 
I'm closing this issue, as our problem will be fixed in the separate repo.
